=== uyk/HanaTI_Workspace/XMLStudy/WebContent/dtd/이력서.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ELEMENT profile (personalinfo,academic+,technology*,global*,otherinfo,family*,prospect)>
	<!ELEMENT personalinfo (name,jumin,gender,age,address,phone,email,businesspart)>
		<!ATTLIST personalinfo from CDATA #FIXED "한국" 
                               image CDATA #REQUIRED>
		<!ELEMENT name (korean, english, chinese?)>
			<!ELEMENT korean (#PCDATA)>
			<!ELEMENT english (#PCDATA)>
			<!ELEMENT chinese (#PCDATA)>
		<!ELEMENT jumin (#PCDATA)>
		<!ELEMENT gender (#PCDATA)>
		<!ELEMENT age (#PCDATA)>
		<!ELEMENT address (#PCDATA)>
		<!ELEMENT phone (#PCDATA)>
		<!ELEMENT email (#PCDATA)>
		<!ELEMENT businesspart (#PCDATA)>
	<!ELEMENT academic (period,school,major,graduation,point)>
		<!ELEMENT period (#PCDATA)>
		<!ELEMENT school (#PCDATA)>
		<!ELEMENT major (#PCDATA)>
		<!ELEMENT graduation (#PCDATA)>
		<!ELEMENT point (#PCDATA)>
	<!ELEMENT technology (computationtech*,languagecert*,computationcert*)>
		<!ELEMENT computationtech (#PCDATA)>
		<!ELEMENT languagecert (#PCDATA)>
		<!ELEMENT computationcert (#PCDATA)>
	<!ELEMENT global (nation,gperiod,purpose)>
		<!ELEMENT nation (#PCDATA)>
		<!ELEMENT gperiod (#PCDATA)>
		<!ELEMENT purpose (#PCDATA)>
	<!ELEMENT otherinfo (brothers,habitation,hobby?,religion?)>
		<!ELEMENT brothers (#PCDATA)>
		<!ELEMENT habitation (#PCDATA)>
		<!ELEMENT hobby (#PCDATA)>
		<!ELEMENT religion (#PCDATA)>
	<!ELEMENT family (fname,fage,scholarship,joblocation,position,livingtogether)>
		<!ELEMENT fname (#PCDATA)>
		<!ELEMENT fage (#PCDATA)>
		<!ELEMENT scholarship (#PCDATA)>
		<!ELEMENT joblocation (#PCDATA)>
		<!ELEMENT position (#PCDATA)>
		<!ELEMENT livingtogether (#PCDATA)>
	<!ELEMENT prospect (salary,entering)>
		<!ELEMENT salary (#PCDATA)>
		<!ELEMENT entering (#PCDATA)>
		

<!ATTLIST academic kind CDATA #REQUIRED daynight CDATA "주간">
<!ATTLIST languagecert language CDATA #REQUIRED>
<!ATTLIST family relation CDATA #REQUIRED>

=== uyk/HanaTI_Workspace/XMLStudy/WebContent/dtd/이력서.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE profile SYSTEM "이력서.dtd">

<profile>
	<!-- 개인정보 -->
	<personalinfo image="myimage.jpg" from="한국">
		<name>
			<korean>김기정</korean>
			<english>Ki Jung Kim</english>
			<chinese>金基正</chinese>
		</name>
		<jumin>111111-1111111</jumin>
		<gender>남</gender>
		<age>20</age>
		<address>서울시 강남구 역삼동</address>
		<phone>010-1111-2222</phone>
		<email>aaa@naver.com</email>
		<businesspart>자바 솔루션 / 웹 개발</businesspart>
	</personalinfo>
	
	<!-- 학력 -->
	<academic kind="고등학교">
		<period>1999.03-2002.02</period>
		<school>ㅇㅇ고등학교</school>
		<major>ㅇㅇㅇ</major>
		<graduation>졸업</graduation>
		<point>4.5/4.5</point>
	</academic>
	<academic kind="대학교" daynight="주간">
		<period>2002.03-2009.02</period>
		<school>ㅇㅇㅇ대학교</school>
		<major>ㅇㅇㅇ</major>
		<graduation>졸업</graduation>
		<point>4.5/4.5</point>
	</academic>
	
	<!-- 보유기술 -->
	<technology>
		<computationtech>Java</computationtech>
		<computationtech>XML</computationtech>
		<languagecert language="English">TOEIC 990</languagecert>
		<computationcert>SCJP</computationcert>
		<computationcert>정보처리기사</computationcert>
	</technology>
	
	<!-- 해외경험 -->
	<global>
		<nation>미국</nation>
		<gperiod>2005.03-2006.02</gperiod>
		<purpose>어학연수</purpose>
	</global>
	<global>
		<nation>일본</nation>
		<gperiod>2006.03-2007.02</gperiod>
		<purpose>놀러</purpose>
	</global>
	
	<!-- 기타 정보 -->
	<otherinfo>
		<brothers>1남 1녀</brothers>
		<habitation>자가</habitation>
		<hobby>놀기</hobby>
		<religion>기독교</religion>
	</otherinfo>
	
	<!-- 가족사항 -->
	<family relation="모">
		<fname>ㅇㅇㅇ</fname>
		<fage>50</fage>
		<scholarship>고졸</scholarship>
		<joblocation>집이지.</joblocation>
		<position>대장</position>
		<livingtogether>예</livingtogether>
	</family>
	<family relation="누나">
		<fname>ㅇㅇㅇ</fname>
		<fage>20</fage>
		<scholarship>대졸</scholarship>
		<joblocation>병원</joblocation>
		<position>간호사</position>
		<livingtogether>예</livingtogether>
	</family>
	
	<!-- 희망연봉 -->
	<prospect>
		<salary>회사내규에 따름</salary>
		<entering>2005년 6월 중(수시)</entering>
	</prospect>	
</profile>
